version: '3.4'

services:
    challenge.api:
        image: ${DOCKER_REGISTRY-}challengeapi
        build:
            context: .
            dockerfile: Challenge.Api/Dockerfile
        ports:
            - "80:80"
            - "443:443"
        environment:
            - ASPNETCORE_ENVIRONMENT=$NET_ENVIRONMENT
            - ASPNETCORE_URLS=https://+:443;http://+:80
        volumes:
            - ~/.aspnet/https:/root/.aspnet/https:ro
            - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
        depends_on:
            - db
            - elasticsearch

    db:
        image: mcr.microsoft.com/mssql/server:$SQL_VERSION
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=$SQL_SA_PASSWORD
        ports:
            - "1433:1433"

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
        environment:
            - xpack.monitoring.enabled=true
            - xpack.watcher.enabled=false
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
            - bootstrap.memory_lock=true            
        ports:
          - "9200:9200"




    
    

